# This workflow will install Python dependencies and run the implemented unittests

name: ci-python-unitest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.80
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install_linux
      run: |
        python -m pip install --upgrade pip
        pip install -e vascu_ec
        
    - name: Running_linux
      run: |
        cd vascu_ec/
        python -m unittest

        
  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.80
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install_windows
      run: |
        python -m pip install --upgrade pip
        pip install -e vascu_ec
        
    - name: Running_windows
      run: |
        cd vascu_ec/
        python -m unittest
        
  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.80
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install_macos
      run: |
        python -m pip install --upgrade pip
        pip install -e vascu_ec
        
    - name: Running_macos
      run: |
        cd vascu_ec/
        python -m unittest
